// Code generated by 0xsequence/devops. DO NOT EDIT.
// Version: 1f7b53c3878961f6372b6db3b29abfeabdb5df41
package networks

// All supported networks
var (
	MAINNET = Network{
		ChainID: 1,
		Name:    "mainnet",
		Title:   "Ethereum",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/1.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherscan",
			RootURL: "https://etherscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
		ENSAddress: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
	}
	ROPSTEN = Network{
		ChainID: 3,
		Name:    "ropsten",
		Title:   "Ropsten",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/3.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherscan (Ropsten)",
			RootURL: "https://ropsten.etherscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "roETH",
			Name:     "Ropsten Ether",
			Decimals: 18,
		},
		ENSAddress: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
		Deprecated: true,
	}
	RINKEBY = Network{
		ChainID: 4,
		Name:    "rinkeby",
		Title:   "Rinkeby",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/4.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherscan (Rinkeby)",
			RootURL: "https://rinkeby.etherscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "rETH",
			Name:     "Rinkeby Ether",
			Decimals: 18,
		},
		ENSAddress: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
		Deprecated: true,
	}
	GOERLI = Network{
		ChainID: 5,
		Name:    "goerli",
		Title:   "Goerli",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/5.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherscan (Goerli)",
			RootURL: "https://goerli.etherscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "gETH",
			Name:     "Goerli Ether",
			Decimals: 18,
		},
		ENSAddress: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
		Deprecated: true,
	}
	OPTIMISM = Network{
		ChainID: 10,
		Name:    "optimism",
		Title:   "Optimism",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/10.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherscan (Optimism)",
			RootURL: "https://optimistic.etherscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	TELOS = Network{
		ChainID: 40,
		Name:    "telos",
		Title:   "Telos",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/40.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Telos Explorer",
			RootURL: "https://explorer.telos.net/network/",
		},
		NativeToken: &Currency{
			Symbol:   "TLOS",
			Name:     "TLOS",
			Decimals: 18,
		},
	}
	TELOS_TESTNET = Network{
		ChainID: 41,
		Name:    "telos-testnet",
		Title:   "Telos Testnet",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/41.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Telos Testnet Explorer",
			RootURL: "https://explorer-test.telos.net/network",
		},
		NativeToken: &Currency{
			Symbol:   "TLOS",
			Name:     "TLOS",
			Decimals: 18,
		},
	}
	KOVAN = Network{
		ChainID: 42,
		Name:    "kovan",
		Title:   "Kovan",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/42.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherscan (Kovan)",
			RootURL: "https://kovan.etherscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "kETH",
			Name:     "Kovan Ether",
			Decimals: 18,
		},
		Deprecated: true,
	}
	BSC = Network{
		ChainID: 56,
		Name:    "bsc",
		Title:   "BNB Smart Chain",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/56.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "BSCScan",
			RootURL: "https://bscscan.com/",
		},
		NativeToken: &Currency{
			Symbol:   "BNB",
			Name:     "BNB",
			Decimals: 18,
		},
	}
	OPTIMISM_KOVAN = Network{
		ChainID: 69,
		Name:    "optimism-kovan",
		Title:   "Optimism Kovan",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/69.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherscan (Optimism Kovan)",
			RootURL: "https://kovan-optimistic.etherscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "kETH",
			Name:     "Kovan Ether",
			Decimals: 18,
		},
		Deprecated: true,
	}
	BSC_TESTNET = Network{
		ChainID: 97,
		Name:    "bsc-testnet",
		Title:   "BNB Smart Chain Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/97.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "BSCScan (Testnet)",
			RootURL: "https://testnet.bscscan.com/",
		},
		NativeToken: &Currency{
			Symbol:   "tBNB",
			Name:     "Testnet BNB",
			Decimals: 18,
		},
	}
	GNOSIS = Network{
		ChainID: 100,
		Name:    "gnosis",
		Title:   "Gnosis Chain",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/100.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Gnosis Chain Explorer",
			RootURL: "https://blockscout.com/xdai/mainnet/",
		},
		NativeToken: &Currency{
			Symbol:   "XDAI",
			Name:     "XDAI",
			Decimals: 18,
		},
	}
	POLYGON = Network{
		ChainID: 137,
		Name:    "polygon",
		Title:   "Polygon",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/137.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Polygonscan",
			RootURL: "https://polygonscan.com/",
		},
		NativeToken: &Currency{
			Symbol:   "POL",
			Name:     "POL",
			Decimals: 18,
		},
	}
	MONAD = Network{
		ChainID: 143,
		Name:    "monad",
		Title:   "Monad",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/143.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Monad Explorer",
			RootURL: "https://mainnet-beta.monvision.io/",
		},
		NativeToken: &Currency{
			Symbol:   "MON",
			Name:     "MON",
			Decimals: 18,
		},
	}
	OPTIMISM_GOERLI = Network{
		ChainID: 420,
		Name:    "optimism-goerli",
		Title:   "Optimism Goerli",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/420.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherscan (Optimism Goerli)",
			RootURL: "https://goerli-optimistic.etherscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "gETH",
			Name:     "Goerli Ether",
			Decimals: 18,
		},
		Deprecated: true,
	}
	POLYGON_ZKEVM = Network{
		ChainID: 1101,
		Name:    "polygon-zkevm",
		Title:   "Polygon zkEVM",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/1101.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Polygonscan (zkEVM)",
			RootURL: "https://zkevm.polygonscan.com/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	MOONBEAM = Network{
		ChainID: 1284,
		Name:    "moonbeam",
		Title:   "Moonbeam",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/1284.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Moonscan",
			RootURL: "https://moonscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "GLMR",
			Name:     "GLMR",
			Decimals: 18,
		},
	}
	MOONBASE_ALPHA = Network{
		ChainID: 1287,
		Name:    "moonbase-alpha",
		Title:   "Moonbase Alpha",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/1287.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Moonscan (Moonbase Alpha)",
			RootURL: "https://moonbase.moonscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "GLMR",
			Name:     "GLMR",
			Decimals: 18,
		},
	}
	SEI_TESTNET = Network{
		ChainID: 1328,
		Name:    "sei-testnet",
		Title:   "Sei Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/1328.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Sei Testnet Explorer",
			RootURL: "https://seitrace.com/?chain=atlantic-2",
		},
		NativeToken: &Currency{
			Symbol:   "SEI",
			Name:     "SEI",
			Decimals: 18,
		},
	}
	SEI = Network{
		ChainID: 1329,
		Name:    "sei",
		Title:   "Sei",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/1329.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "SEI Explorer",
			RootURL: "https://seitrace.com/?chain=pacific-1",
		},
		NativeToken: &Currency{
			Symbol:   "SEI",
			Name:     "SEI",
			Decimals: 18,
		},
	}
	SONEIUM = Network{
		ChainID: 1868,
		Name:    "soneium",
		Title:   "Soneium",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/1868.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Soneium Explorer",
			RootURL: "https://soneium.blockscout.com/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	SONEIUM_MINATO = Network{
		ChainID: 1946,
		Name:    "soneium-minato",
		Title:   "Soneium Minato (Testnet)",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/1946.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Soneium Minato Explorer",
			RootURL: "https://explorer-testnet.soneium.org/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	B3_SEPOLIA = Network{
		ChainID: 1993,
		Name:    "b3-sepolia",
		Title:   "B3 Sepolia",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/1993.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "B3 Sepolia Explorer",
			RootURL: "https://sepolia.explorer.b3.fun/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	SOMNIA = Network{
		ChainID: 5031,
		Name:    "somnia",
		Title:   "Somnia",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/5031.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Somnia Explorer",
			RootURL: "https://mainnet.somnia.w3us.site/",
		},
		NativeToken: &Currency{
			Symbol:   "SOMI",
			Name:     "SOMI",
			Decimals: 18,
		},
	}
	SANDBOX_TESTNET = Network{
		ChainID: 6252,
		Name:    "sandbox-testnet",
		Title:   "Sandbox Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/6252.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Sandbox Testnet Explorer",
			RootURL: "https://sandbox-testnet.explorer.caldera.xyz/",
		},
		NativeToken: &Currency{
			Symbol:   "SAND",
			Name:     "SAND",
			Decimals: 18,
		},
	}
	B3 = Network{
		ChainID: 8333,
		Name:    "b3",
		Title:   "B3",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/8333.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "B3 Explorer",
			RootURL: "https://explorer.b3.fun/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	BASE = Network{
		ChainID: 8453,
		Name:    "base",
		Title:   "Base (Coinbase)",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/8453.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Base Explorer",
			RootURL: "https://basescan.org/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	MONAD_TESTNET = Network{
		ChainID: 10143,
		Name:    "monad-testnet",
		Title:   "Monad Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/10143.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Monad Testnet Explorer",
			RootURL: "https://testnet.monadexplorer.com/",
		},
		NativeToken: &Currency{
			Symbol:   "MON",
			Name:     "MON",
			Decimals: 18,
		},
	}
	INCENTIV_TESTNET = Network{
		ChainID: 11690,
		Name:    "incentiv-testnet",
		Title:   "Incentiv Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/11690.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Incentiv Testnet Explorer",
			RootURL: "https://explorer.testnet.incentiv.net/",
		},
		NativeToken: &Currency{
			Symbol:   "CENT",
			Name:     "CENT",
			Decimals: 18,
		},
		Deprecated: true,
	}
	IMMUTABLE_ZKEVM = Network{
		ChainID: 13371,
		Name:    "immutable-zkevm",
		Title:   "Immutable zkEVM",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/13371.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Immutable zkEVM Explorer",
			RootURL: "https://explorer.immutable.com/",
		},
		NativeToken: &Currency{
			Symbol:   "IMX",
			Name:     "IMX",
			Decimals: 18,
		},
	}
	IMMUTABLE_ZKEVM_TESTNET = Network{
		ChainID: 13473,
		Name:    "immutable-zkevm-testnet",
		Title:   "Immutable zkEVM Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/13473.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Immutable zkEVM Testnet Explorer",
			RootURL: "https://explorer.testnet.immutable.com/",
		},
		NativeToken: &Currency{
			Symbol:   "IMX",
			Name:     "IMX",
			Decimals: 18,
		},
	}
	HOMEVERSE = Network{
		ChainID: 19011,
		Name:    "homeverse",
		Title:   "Oasys Homeverse",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/19011.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Oasys Homeverse Explorer",
			RootURL: "https://explorer.oasys.homeverse.games/",
		},
		NativeToken: &Currency{
			Symbol:   "OAS",
			Name:     "OAS",
			Decimals: 18,
		},
	}
	INCENTIV = Network{
		ChainID: 24101,
		Name:    "incentiv",
		Title:   "Incentiv",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/24101.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Incentiv",
			RootURL: "https://explorer.incentiv.io/",
		},
		NativeToken: &Currency{
			Symbol:   "CENT",
			Name:     "CENT",
			Decimals: 18,
		},
	}
	INCENTIV_TESTNET_V2 = Network{
		ChainID: 28802,
		Name:    "incentiv-testnet-v2",
		Title:   "Incentiv Testnet v2",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/28802.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Incentiv Testnet Explorer v2",
			RootURL: "https://explorer.testnet.incentiv.net/",
		},
		NativeToken: &Currency{
			Symbol:   "TCENT",
			Name:     "TCENT",
			Decimals: 18,
		},
	}
	HARDHAT = Network{
		ChainID: 31337,
		Name:    "hardhat",
		Title:   "Hardhat (local testnet)",
		Type:    NetworkTypeMainnet,
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	HARDHAT2 = Network{
		ChainID: 31338,
		Name:    "hardhat2",
		Title:   "Hardhat (local testnet)",
		Type:    NetworkTypeMainnet,
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	APECHAIN_TESTNET = Network{
		ChainID: 33111,
		Name:    "apechain-testnet",
		Title:   "APE Chain Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/33111.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "APE Chain Explorer",
			RootURL: "https://curtis.explorer.caldera.xyz/",
		},
		NativeToken: &Currency{
			Symbol:   "APE",
			Name:     "ApeCoin",
			Decimals: 18,
		},
	}
	APECHAIN = Network{
		ChainID: 33139,
		Name:    "apechain",
		Title:   "APE Chain",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/33139.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "APE Chain Explorer",
			RootURL: "https://apechain.calderaexplorer.xyz/",
		},
		NativeToken: &Currency{
			Symbol:   "APE",
			Name:     "ApeCoin",
			Decimals: 18,
		},
	}
	HOMEVERSE_TESTNET = Network{
		ChainID: 40875,
		Name:    "homeverse-testnet",
		Title:   "Oasys Homeverse Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/40875.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Oasys Homeverse Explorer (Testnet)",
			RootURL: "https://explorer.testnet.oasys.homeverse.games/",
		},
		NativeToken: &Currency{
			Symbol:   "tOAS",
			Name:     "Testnet OAS",
			Decimals: 18,
		},
	}
	ARBITRUM = Network{
		ChainID: 42161,
		Name:    "arbitrum",
		Title:   "Arbitrum One",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/42161.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Arbiscan",
			RootURL: "https://arbiscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	ARBITRUM_NOVA = Network{
		ChainID: 42170,
		Name:    "arbitrum-nova",
		Title:   "Arbitrum Nova",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/42170.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Arbiscan Nova",
			RootURL: "https://nova.arbiscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	ETHERLINK = Network{
		ChainID: 42793,
		Name:    "etherlink",
		Title:   "Etherlink",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/42793.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherlink Explorer",
			RootURL: "https://explorer.etherlink.com/",
		},
		NativeToken: &Currency{
			Symbol:   "XTZ",
			Name:     "Tez",
			Decimals: 18,
		},
	}
	AVALANCHE_TESTNET = Network{
		ChainID: 43113,
		Name:    "avalanche-testnet",
		Title:   "Avalanche Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/43113.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Snowtrace (Testnet)",
			RootURL: "https://subnets-test.avax.network/c-chain/",
		},
		NativeToken: &Currency{
			Symbol:   "tAVAX",
			Name:     "Testnet AVAX",
			Decimals: 18,
		},
	}
	AVALANCHE = Network{
		ChainID: 43114,
		Name:    "avalanche",
		Title:   "Avalanche",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/43114.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Snowtrace",
			RootURL: "https://subnets.avax.network/c-chain/",
		},
		NativeToken: &Currency{
			Symbol:   "AVAX",
			Name:     "AVAX",
			Decimals: 18,
		},
	}
	SOMNIA_TESTNET = Network{
		ChainID: 50312,
		Name:    "somnia-testnet",
		Title:   "Somnia Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/50312.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Somnia Testnet Explorer",
			RootURL: "https://shannon-explorer.somnia.network/",
		},
		NativeToken: &Currency{
			Symbol:   "STT",
			Name:     "STT",
			Decimals: 18,
		},
	}
	MUMBAI = Network{
		ChainID: 80001,
		Name:    "mumbai",
		Title:   "Polygon Mumbai",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/80001.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Polygonscan (Mumbai)",
			RootURL: "https://mumbai.polygonscan.com/",
		},
		NativeToken: &Currency{
			Symbol:   "mMATIC",
			Name:     "Mumbai Polygon",
			Decimals: 18,
		},
		Deprecated: true,
	}
	AMOY = Network{
		ChainID: 80002,
		Name:    "amoy",
		Title:   "Polygon Amoy",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/80002.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "OKLink (Amoy)",
			RootURL: "https://www.oklink.com/amoy/",
		},
		NativeToken: &Currency{
			Symbol:   "aPOL",
			Name:     "Amoy POL",
			Decimals: 18,
		},
	}
	BLAST = Network{
		ChainID: 81457,
		Name:    "blast",
		Title:   "Blast",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/81457.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Blast Explorer",
			RootURL: "https://blastscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	BASE_GOERLI = Network{
		ChainID: 84531,
		Name:    "base-goerli",
		Title:   "Base Goerli",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/84531.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Base Goerli Explorer",
			RootURL: "https://goerli.basescan.org/",
		},
		NativeToken: &Currency{
			Symbol:   "gETH",
			Name:     "Goerli Ether",
			Decimals: 18,
		},
		Deprecated: true,
	}
	BASE_SEPOLIA = Network{
		ChainID: 84532,
		Name:    "base-sepolia",
		Title:   "Base Sepolia",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/84532.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Base Sepolia Explorer",
			RootURL: "https://base-sepolia.blockscout.com/",
		},
		NativeToken: &Currency{
			Symbol:   "sETH",
			Name:     "Sepolia Ether",
			Decimals: 18,
		},
	}
	BORNE_TESTNET = Network{
		ChainID: 94984,
		Name:    "borne-testnet",
		Title:   "Borne Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/94984.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Borne Testnet Explorer",
			RootURL: "https://subnets-test.avax.network/bornegfdn",
		},
		NativeToken: &Currency{
			Symbol:   "BORNE",
			Name:     "BORNE",
			Decimals: 18,
		},
		Deprecated: true,
	}
	ETHERLINK_SHADOWNET_TESTNET = Network{
		ChainID: 127823,
		Name:    "etherlink-shadownet-testnet",
		Title:   "Etherlink Shadownet Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/127823.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherlink Shadownet Testnet Explorer",
			RootURL: "https://shadownet.explorer.etherlink.com/",
		},
		NativeToken: &Currency{
			Symbol:   "XTZ",
			Name:     "Tez",
			Decimals: 18,
		},
	}
	ETHERLINK_TESTNET = Network{
		ChainID: 128123,
		Name:    "etherlink-testnet",
		Title:   "Etherlink Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/128123.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherlink Testnet Explorer",
			RootURL: "https://testnet.explorer.etherlink.com/",
		},
		NativeToken: &Currency{
			Symbol:   "XTZ",
			Name:     "Tez",
			Decimals: 18,
		},
	}
	ARBITRUM_GOERLI = Network{
		ChainID: 421613,
		Name:    "arbitrum-goerli",
		Title:   "Arbitrum Goerli",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/421613.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Arbiscan (Goerli Testnet)",
			RootURL: "https://testnet.arbiscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "gETH",
			Name:     "Goerli Ether",
			Decimals: 18,
		},
		Deprecated: true,
	}
	ARBITRUM_SEPOLIA = Network{
		ChainID: 421614,
		Name:    "arbitrum-sepolia",
		Title:   "Arbitrum Sepolia",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/421614.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Arbiscan (Sepolia Testnet)",
			RootURL: "https://sepolia.arbiscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "sETH",
			Name:     "Sepolia Ether",
			Decimals: 18,
		},
	}
	XAI = Network{
		ChainID: 660279,
		Name:    "xai",
		Title:   "Xai",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/660279.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Xai Explorer",
			RootURL: "https://explorer.xai-chain.net/",
		},
		NativeToken: &Currency{
			Symbol:   "XAI",
			Name:     "XAI",
			Decimals: 18,
		},
	}
	KATANA = Network{
		ChainID: 747474,
		Name:    "katana",
		Title:   "Katana",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/747474.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Katana",
			RootURL: "https://katanascan.com/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "ETH",
			Decimals: 18,
		},
	}
	ARC_TESTNET = Network{
		ChainID: 5042002,
		Name:    "arc-testnet",
		Title:   "Arc Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/5042002.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Arc Testnet Explorer",
			RootURL: "https://testnet.arcscan.app/",
		},
		NativeToken: &Currency{
			Symbol:   "USDC",
			Name:     "USDC",
			Decimals: 18,
		},
	}
	SEPOLIA = Network{
		ChainID: 11155111,
		Name:    "sepolia",
		Title:   "Sepolia",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/11155111.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherscan (Sepolia)",
			RootURL: "https://sepolia.etherscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "sETH",
			Name:     "Sepolia Ether",
			Decimals: 18,
		},
	}
	OPTIMISM_SEPOLIA = Network{
		ChainID: 11155420,
		Name:    "optimism-sepolia",
		Title:   "Optimism Sepolia",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/11155420.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Etherscan (Optimism Sepolia)",
			RootURL: "https://sepolia-optimistic.etherscan.io/",
		},
		NativeToken: &Currency{
			Symbol:   "sETH",
			Name:     "Sepolia Ether",
			Decimals: 18,
		},
	}
	TOY_TESTNET = Network{
		ChainID: 21000000,
		Name:    "toy-testnet",
		Title:   "TOY (Testnet)",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/21000000.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "TOY Testnet Explorer",
			RootURL: "https://toy-chain-testnet.explorer.caldera.xyz/",
		},
		NativeToken: &Currency{
			Symbol:   "TOY",
			Name:     "TOY",
			Decimals: 18,
		},
	}
	SKALE_NEBULA_TESTNET = Network{
		ChainID: 37084624,
		Name:    "skale-nebula-testnet",
		Title:   "SKALE Nebula Gaming Hub Testnet",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/37084624.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "SKALE Nebula Gaming Hub Testnet Explorer",
			RootURL: "https://lanky-ill-funny-testnet.explorer.testnet.skalenodes.com/",
		},
		NativeToken: &Currency{
			Symbol:   "sFUEL",
			Name:     "SKALE Fuel",
			Decimals: 18,
		},
	}
	BLAST_SEPOLIA = Network{
		ChainID: 168587773,
		Name:    "blast-sepolia",
		Title:   "Blast Sepolia",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/168587773.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Blast Sepolia Explorer",
			RootURL: "https://sepolia.blastexplorer.io/",
		},
		NativeToken: &Currency{
			Symbol:   "ETH",
			Name:     "Ether",
			Decimals: 18,
		},
	}
	SKALE_NEBULA = Network{
		ChainID: 1482601649,
		Name:    "skale-nebula",
		Title:   "SKALE Nebula Gaming Hub",
		Type:    NetworkTypeMainnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/1482601649.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "SKALE Nebula Gaming Hub Explorer",
			RootURL: "https://green-giddy-denebola.explorer.mainnet.skalenodes.com/",
		},
		NativeToken: &Currency{
			Symbol:   "sFUEL",
			Name:     "SKALE Fuel",
			Decimals: 18,
		},
	}
	XAI_SEPOLIA = Network{
		ChainID: 37714555429,
		Name:    "xai-sepolia",
		Title:   "Xai Sepolia",
		Type:    NetworkTypeTestnet,
		LogoURL: "https://assets.sequence.info/images/networks/medium/37714555429.webp",
		BlockExplorer: &BlockExplorerConfig{
			Name:    "Xai Sepolia Explorer",
			RootURL: "https://testnet-explorer-v2.xai-chain.net/",
		},
		NativeToken: &Currency{
			Symbol:   "sXAI",
			Name:     "Sepolia XAI",
			Decimals: 18,
		},
	}
)

var ByName = map[string]*Network{
	"mainnet":                     &MAINNET,
	"ropsten":                     &ROPSTEN,
	"rinkeby":                     &RINKEBY,
	"goerli":                      &GOERLI,
	"optimism":                    &OPTIMISM,
	"telos":                       &TELOS,
	"telos-testnet":               &TELOS_TESTNET,
	"kovan":                       &KOVAN,
	"bsc":                         &BSC,
	"optimism-kovan":              &OPTIMISM_KOVAN,
	"bsc-testnet":                 &BSC_TESTNET,
	"gnosis":                      &GNOSIS,
	"polygon":                     &POLYGON,
	"monad":                       &MONAD,
	"optimism-goerli":             &OPTIMISM_GOERLI,
	"polygon-zkevm":               &POLYGON_ZKEVM,
	"moonbeam":                    &MOONBEAM,
	"moonbase-alpha":              &MOONBASE_ALPHA,
	"sei-testnet":                 &SEI_TESTNET,
	"sei":                         &SEI,
	"soneium":                     &SONEIUM,
	"soneium-minato":              &SONEIUM_MINATO,
	"b3-sepolia":                  &B3_SEPOLIA,
	"somnia":                      &SOMNIA,
	"sandbox-testnet":             &SANDBOX_TESTNET,
	"b3":                          &B3,
	"base":                        &BASE,
	"monad-testnet":               &MONAD_TESTNET,
	"incentiv-testnet":            &INCENTIV_TESTNET,
	"immutable-zkevm":             &IMMUTABLE_ZKEVM,
	"immutable-zkevm-testnet":     &IMMUTABLE_ZKEVM_TESTNET,
	"homeverse":                   &HOMEVERSE,
	"incentiv":                    &INCENTIV,
	"incentiv-testnet-v2":         &INCENTIV_TESTNET_V2,
	"hardhat":                     &HARDHAT,
	"hardhat2":                    &HARDHAT2,
	"apechain-testnet":            &APECHAIN_TESTNET,
	"apechain":                    &APECHAIN,
	"homeverse-testnet":           &HOMEVERSE_TESTNET,
	"arbitrum":                    &ARBITRUM,
	"arbitrum-nova":               &ARBITRUM_NOVA,
	"etherlink":                   &ETHERLINK,
	"avalanche-testnet":           &AVALANCHE_TESTNET,
	"avalanche":                   &AVALANCHE,
	"somnia-testnet":              &SOMNIA_TESTNET,
	"mumbai":                      &MUMBAI,
	"amoy":                        &AMOY,
	"blast":                       &BLAST,
	"base-goerli":                 &BASE_GOERLI,
	"base-sepolia":                &BASE_SEPOLIA,
	"borne-testnet":               &BORNE_TESTNET,
	"etherlink-shadownet-testnet": &ETHERLINK_SHADOWNET_TESTNET,
	"etherlink-testnet":           &ETHERLINK_TESTNET,
	"arbitrum-goerli":             &ARBITRUM_GOERLI,
	"arbitrum-sepolia":            &ARBITRUM_SEPOLIA,
	"xai":                         &XAI,
	"katana":                      &KATANA,
	"arc-testnet":                 &ARC_TESTNET,
	"sepolia":                     &SEPOLIA,
	"optimism-sepolia":            &OPTIMISM_SEPOLIA,
	"toy-testnet":                 &TOY_TESTNET,
	"skale-nebula-testnet":        &SKALE_NEBULA_TESTNET,
	"blast-sepolia":               &BLAST_SEPOLIA,
	"skale-nebula":                &SKALE_NEBULA,
	"xai-sepolia":                 &XAI_SEPOLIA,
}
var ByChainID = map[int]*Network{
	1:           &MAINNET,
	3:           &ROPSTEN,
	4:           &RINKEBY,
	5:           &GOERLI,
	10:          &OPTIMISM,
	40:          &TELOS,
	41:          &TELOS_TESTNET,
	42:          &KOVAN,
	56:          &BSC,
	69:          &OPTIMISM_KOVAN,
	97:          &BSC_TESTNET,
	100:         &GNOSIS,
	137:         &POLYGON,
	143:         &MONAD,
	420:         &OPTIMISM_GOERLI,
	1101:        &POLYGON_ZKEVM,
	1284:        &MOONBEAM,
	1287:        &MOONBASE_ALPHA,
	1328:        &SEI_TESTNET,
	1329:        &SEI,
	1868:        &SONEIUM,
	1946:        &SONEIUM_MINATO,
	1993:        &B3_SEPOLIA,
	5031:        &SOMNIA,
	6252:        &SANDBOX_TESTNET,
	8333:        &B3,
	8453:        &BASE,
	10143:       &MONAD_TESTNET,
	11690:       &INCENTIV_TESTNET,
	13371:       &IMMUTABLE_ZKEVM,
	13473:       &IMMUTABLE_ZKEVM_TESTNET,
	19011:       &HOMEVERSE,
	24101:       &INCENTIV,
	28802:       &INCENTIV_TESTNET_V2,
	31337:       &HARDHAT,
	31338:       &HARDHAT2,
	33111:       &APECHAIN_TESTNET,
	33139:       &APECHAIN,
	40875:       &HOMEVERSE_TESTNET,
	42161:       &ARBITRUM,
	42170:       &ARBITRUM_NOVA,
	42793:       &ETHERLINK,
	43113:       &AVALANCHE_TESTNET,
	43114:       &AVALANCHE,
	50312:       &SOMNIA_TESTNET,
	80001:       &MUMBAI,
	80002:       &AMOY,
	81457:       &BLAST,
	84531:       &BASE_GOERLI,
	84532:       &BASE_SEPOLIA,
	94984:       &BORNE_TESTNET,
	127823:      &ETHERLINK_SHADOWNET_TESTNET,
	128123:      &ETHERLINK_TESTNET,
	421613:      &ARBITRUM_GOERLI,
	421614:      &ARBITRUM_SEPOLIA,
	660279:      &XAI,
	747474:      &KATANA,
	5042002:     &ARC_TESTNET,
	11155111:    &SEPOLIA,
	11155420:    &OPTIMISM_SEPOLIA,
	21000000:    &TOY_TESTNET,
	37084624:    &SKALE_NEBULA_TESTNET,
	168587773:   &BLAST_SEPOLIA,
	1482601649:  &SKALE_NEBULA,
	37714555429: &XAI_SEPOLIA,
}
