// Code generated by MockGen. DO NOT EDIT.
// Source: ./proto (interfaces: Relayer)
//
// Generated by this command:
//
//	mockgen -destination relayer.mock.go -package relayer ./proto Relayer
//

// Package relayer is a generated GoMock package.
package relayer

import (
	context "context"
	reflect "reflect"
	time "time"

	proto "github.com/0xsequence/go-sequence/relayer/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockRelayer is a mock of Relayer interface.
type MockRelayer struct {
	ctrl     *gomock.Controller
	recorder *MockRelayerMockRecorder
	isgomock struct{}
}

// MockRelayerMockRecorder is the mock recorder for MockRelayer.
type MockRelayerMockRecorder struct {
	mock *MockRelayer
}

// NewMockRelayer creates a new mock instance.
func NewMockRelayer(ctrl *gomock.Controller) *MockRelayer {
	mock := &MockRelayer{ctrl: ctrl}
	mock.recorder = &MockRelayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayer) EXPECT() *MockRelayerMockRecorder {
	return m.recorder
}

// AddGasSponsor mocks base method.
func (m *MockRelayer) AddGasSponsor(ctx context.Context, projectId uint64, address string, name *string, active *bool) (bool, *proto.GasSponsor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGasSponsor", ctx, projectId, address, name, active)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*proto.GasSponsor)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddGasSponsor indicates an expected call of AddGasSponsor.
func (mr *MockRelayerMockRecorder) AddGasSponsor(ctx, projectId, address, name, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGasSponsor", reflect.TypeOf((*MockRelayer)(nil).AddGasSponsor), ctx, projectId, address, name, active)
}

// AddGasTank mocks base method.
func (m *MockRelayer) AddGasTank(ctx context.Context, name string, feeMarkupFactor float64, unlimited *bool) (bool, *proto.GasTank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGasTank", ctx, name, feeMarkupFactor, unlimited)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*proto.GasTank)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddGasTank indicates an expected call of AddGasTank.
func (mr *MockRelayerMockRecorder) AddGasTank(ctx, name, feeMarkupFactor, unlimited any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGasTank", reflect.TypeOf((*MockRelayer)(nil).AddGasTank), ctx, name, feeMarkupFactor, unlimited)
}

// AddressGasSponsors mocks base method.
func (m *MockRelayer) AddressGasSponsors(ctx context.Context, address string, page *proto.Page) (*proto.Page, []*proto.GasSponsor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddressGasSponsors", ctx, address, page)
	ret0, _ := ret[0].(*proto.Page)
	ret1, _ := ret[1].([]*proto.GasSponsor)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddressGasSponsors indicates an expected call of AddressGasSponsors.
func (mr *MockRelayerMockRecorder) AddressGasSponsors(ctx, address, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddressGasSponsors", reflect.TypeOf((*MockRelayer)(nil).AddressGasSponsors), ctx, address, page)
}

// AdjustGasTankBalance mocks base method.
func (m *MockRelayer) AdjustGasTankBalance(ctx context.Context, id, nonce uint64, amount float64) (bool, *proto.GasTankBalanceAdjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustGasTankBalance", ctx, id, nonce, amount)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*proto.GasTankBalanceAdjustment)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AdjustGasTankBalance indicates an expected call of AdjustGasTankBalance.
func (mr *MockRelayerMockRecorder) AdjustGasTankBalance(ctx, id, nonce, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustGasTankBalance", reflect.TypeOf((*MockRelayer)(nil).AdjustGasTankBalance), ctx, id, nonce, amount)
}

// AdjustProjectBalance mocks base method.
func (m *MockRelayer) AdjustProjectBalance(ctx context.Context, projectId uint64, amount float64, identifier string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustProjectBalance", ctx, projectId, amount, identifier)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdjustProjectBalance indicates an expected call of AdjustProjectBalance.
func (mr *MockRelayerMockRecorder) AdjustProjectBalance(ctx, projectId, amount, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustProjectBalance", reflect.TypeOf((*MockRelayer)(nil).AdjustProjectBalance), ctx, projectId, amount, identifier)
}

// FeeOptions mocks base method.
func (m *MockRelayer) FeeOptions(ctx context.Context, wallet, to, data string, simulate *bool) ([]*proto.FeeOption, bool, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeeOptions", ctx, wallet, to, data, simulate)
	ret0, _ := ret[0].([]*proto.FeeOption)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(*string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// FeeOptions indicates an expected call of FeeOptions.
func (mr *MockRelayerMockRecorder) FeeOptions(ctx, wallet, to, data, simulate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeeOptions", reflect.TypeOf((*MockRelayer)(nil).FeeOptions), ctx, wallet, to, data, simulate)
}

// FeeTokens mocks base method.
func (m *MockRelayer) FeeTokens(ctx context.Context) (bool, []*proto.FeeToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeeTokens", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]*proto.FeeToken)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FeeTokens indicates an expected call of FeeTokens.
func (mr *MockRelayerMockRecorder) FeeTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeeTokens", reflect.TypeOf((*MockRelayer)(nil).FeeTokens), ctx)
}

// GetChainID mocks base method.
func (m *MockRelayer) GetChainID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChainID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChainID indicates an expected call of GetChainID.
func (mr *MockRelayerMockRecorder) GetChainID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainID", reflect.TypeOf((*MockRelayer)(nil).GetChainID), ctx)
}

// GetGasSponsor mocks base method.
func (m *MockRelayer) GetGasSponsor(ctx context.Context, projectId, id uint64) (*proto.GasSponsor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGasSponsor", ctx, projectId, id)
	ret0, _ := ret[0].(*proto.GasSponsor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGasSponsor indicates an expected call of GetGasSponsor.
func (mr *MockRelayerMockRecorder) GetGasSponsor(ctx, projectId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGasSponsor", reflect.TypeOf((*MockRelayer)(nil).GetGasSponsor), ctx, projectId, id)
}

// GetGasTank mocks base method.
func (m *MockRelayer) GetGasTank(ctx context.Context, id uint64) (*proto.GasTank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGasTank", ctx, id)
	ret0, _ := ret[0].(*proto.GasTank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGasTank indicates an expected call of GetGasTank.
func (mr *MockRelayerMockRecorder) GetGasTank(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGasTank", reflect.TypeOf((*MockRelayer)(nil).GetGasTank), ctx, id)
}

// GetGasTankBalanceAdjustment mocks base method.
func (m *MockRelayer) GetGasTankBalanceAdjustment(ctx context.Context, id, nonce uint64) (*proto.GasTankBalanceAdjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGasTankBalanceAdjustment", ctx, id, nonce)
	ret0, _ := ret[0].(*proto.GasTankBalanceAdjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGasTankBalanceAdjustment indicates an expected call of GetGasTankBalanceAdjustment.
func (mr *MockRelayerMockRecorder) GetGasTankBalanceAdjustment(ctx, id, nonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGasTankBalanceAdjustment", reflect.TypeOf((*MockRelayer)(nil).GetGasTankBalanceAdjustment), ctx, id, nonce)
}

// GetMetaTransactions mocks base method.
func (m *MockRelayer) GetMetaTransactions(ctx context.Context, projectId uint64, page *proto.Page) (*proto.Page, []*proto.MetaTxnLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaTransactions", ctx, projectId, page)
	ret0, _ := ret[0].(*proto.Page)
	ret1, _ := ret[1].([]*proto.MetaTxnLog)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMetaTransactions indicates an expected call of GetMetaTransactions.
func (mr *MockRelayerMockRecorder) GetMetaTransactions(ctx, projectId, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaTransactions", reflect.TypeOf((*MockRelayer)(nil).GetMetaTransactions), ctx, projectId, page)
}

// GetMetaTxnNetworkFeeOptions mocks base method.
func (m *MockRelayer) GetMetaTxnNetworkFeeOptions(ctx context.Context, walletConfig any, payload string) ([]*proto.FeeOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaTxnNetworkFeeOptions", ctx, walletConfig, payload)
	ret0, _ := ret[0].([]*proto.FeeOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaTxnNetworkFeeOptions indicates an expected call of GetMetaTxnNetworkFeeOptions.
func (mr *MockRelayerMockRecorder) GetMetaTxnNetworkFeeOptions(ctx, walletConfig, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaTxnNetworkFeeOptions", reflect.TypeOf((*MockRelayer)(nil).GetMetaTxnNetworkFeeOptions), ctx, walletConfig, payload)
}

// GetMetaTxnNonce mocks base method.
func (m *MockRelayer) GetMetaTxnNonce(ctx context.Context, walletContractAddress string, space *string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaTxnNonce", ctx, walletContractAddress, space)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaTxnNonce indicates an expected call of GetMetaTxnNonce.
func (mr *MockRelayerMockRecorder) GetMetaTxnNonce(ctx, walletContractAddress, space any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaTxnNonce", reflect.TypeOf((*MockRelayer)(nil).GetMetaTxnNonce), ctx, walletContractAddress, space)
}

// GetMetaTxnReceipt mocks base method.
func (m *MockRelayer) GetMetaTxnReceipt(ctx context.Context, metaTxID string) (*proto.MetaTxnReceipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaTxnReceipt", ctx, metaTxID)
	ret0, _ := ret[0].(*proto.MetaTxnReceipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaTxnReceipt indicates an expected call of GetMetaTxnReceipt.
func (mr *MockRelayerMockRecorder) GetMetaTxnReceipt(ctx, metaTxID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaTxnReceipt", reflect.TypeOf((*MockRelayer)(nil).GetMetaTxnReceipt), ctx, metaTxID)
}

// GetProjectBalance mocks base method.
func (m *MockRelayer) GetProjectBalance(ctx context.Context, projectId uint64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectBalance", ctx, projectId)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectBalance indicates an expected call of GetProjectBalance.
func (mr *MockRelayerMockRecorder) GetProjectBalance(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectBalance", reflect.TypeOf((*MockRelayer)(nil).GetProjectBalance), ctx, projectId)
}

// GetSequenceContext mocks base method.
func (m *MockRelayer) GetSequenceContext(ctx context.Context) (*proto.SequenceContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSequenceContext", ctx)
	ret0, _ := ret[0].(*proto.SequenceContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSequenceContext indicates an expected call of GetSequenceContext.
func (mr *MockRelayerMockRecorder) GetSequenceContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSequenceContext", reflect.TypeOf((*MockRelayer)(nil).GetSequenceContext), ctx)
}

// GetTransactionCost mocks base method.
func (m *MockRelayer) GetTransactionCost(ctx context.Context, projectId uint64, from, to time.Time) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionCost", ctx, projectId, from, to)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionCost indicates an expected call of GetTransactionCost.
func (mr *MockRelayerMockRecorder) GetTransactionCost(ctx, projectId, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionCost", reflect.TypeOf((*MockRelayer)(nil).GetTransactionCost), ctx, projectId, from, to)
}

// ListGasSponsors mocks base method.
func (m *MockRelayer) ListGasSponsors(ctx context.Context, projectId uint64, page *proto.Page) (*proto.Page, []*proto.GasSponsor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGasSponsors", ctx, projectId, page)
	ret0, _ := ret[0].(*proto.Page)
	ret1, _ := ret[1].([]*proto.GasSponsor)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGasSponsors indicates an expected call of ListGasSponsors.
func (mr *MockRelayerMockRecorder) ListGasSponsors(ctx, projectId, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGasSponsors", reflect.TypeOf((*MockRelayer)(nil).ListGasSponsors), ctx, projectId, page)
}

// ListGasTankBalanceAdjustments mocks base method.
func (m *MockRelayer) ListGasTankBalanceAdjustments(ctx context.Context, id uint64, page *proto.Page) (*proto.Page, []*proto.GasTankBalanceAdjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGasTankBalanceAdjustments", ctx, id, page)
	ret0, _ := ret[0].(*proto.Page)
	ret1, _ := ret[1].([]*proto.GasTankBalanceAdjustment)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGasTankBalanceAdjustments indicates an expected call of ListGasTankBalanceAdjustments.
func (mr *MockRelayerMockRecorder) ListGasTankBalanceAdjustments(ctx, id, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGasTankBalanceAdjustments", reflect.TypeOf((*MockRelayer)(nil).ListGasTankBalanceAdjustments), ctx, id, page)
}

// NextGasTankBalanceAdjustmentNonce mocks base method.
func (m *MockRelayer) NextGasTankBalanceAdjustmentNonce(ctx context.Context, id uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextGasTankBalanceAdjustmentNonce", ctx, id)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextGasTankBalanceAdjustmentNonce indicates an expected call of NextGasTankBalanceAdjustmentNonce.
func (mr *MockRelayerMockRecorder) NextGasTankBalanceAdjustmentNonce(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextGasTankBalanceAdjustmentNonce", reflect.TypeOf((*MockRelayer)(nil).NextGasTankBalanceAdjustmentNonce), ctx, id)
}

// PendingTransactions mocks base method.
func (m *MockRelayer) PendingTransactions(ctx context.Context, page *proto.Page) (*proto.Page, []*proto.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingTransactions", ctx, page)
	ret0, _ := ret[0].(*proto.Page)
	ret1, _ := ret[1].([]*proto.Transaction)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PendingTransactions indicates an expected call of PendingTransactions.
func (mr *MockRelayerMockRecorder) PendingTransactions(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingTransactions", reflect.TypeOf((*MockRelayer)(nil).PendingTransactions), ctx, page)
}

// Ping mocks base method.
func (m *MockRelayer) Ping(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ping indicates an expected call of Ping.
func (mr *MockRelayerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRelayer)(nil).Ping), ctx)
}

// RemoveGasSponsor mocks base method.
func (m *MockRelayer) RemoveGasSponsor(ctx context.Context, projectId, id uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGasSponsor", ctx, projectId, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveGasSponsor indicates an expected call of RemoveGasSponsor.
func (mr *MockRelayerMockRecorder) RemoveGasSponsor(ctx, projectId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGasSponsor", reflect.TypeOf((*MockRelayer)(nil).RemoveGasSponsor), ctx, projectId, id)
}

// RuntimeStatus mocks base method.
func (m *MockRelayer) RuntimeStatus(ctx context.Context) (*proto.RuntimeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RuntimeStatus", ctx)
	ret0, _ := ret[0].(*proto.RuntimeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RuntimeStatus indicates an expected call of RuntimeStatus.
func (mr *MockRelayerMockRecorder) RuntimeStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RuntimeStatus", reflect.TypeOf((*MockRelayer)(nil).RuntimeStatus), ctx)
}

// SendMetaTxn mocks base method.
func (m *MockRelayer) SendMetaTxn(ctx context.Context, call *proto.MetaTxn, quote *string, projectID *uint64) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMetaTxn", ctx, call, quote, projectID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendMetaTxn indicates an expected call of SendMetaTxn.
func (mr *MockRelayerMockRecorder) SendMetaTxn(ctx, call, quote, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMetaTxn", reflect.TypeOf((*MockRelayer)(nil).SendMetaTxn), ctx, call, quote, projectID)
}

// SentTransactions mocks base method.
func (m *MockRelayer) SentTransactions(ctx context.Context, filter *proto.SentTransactionsFilter, page *proto.Page) (*proto.Page, []*proto.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SentTransactions", ctx, filter, page)
	ret0, _ := ret[0].(*proto.Page)
	ret1, _ := ret[1].([]*proto.Transaction)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SentTransactions indicates an expected call of SentTransactions.
func (mr *MockRelayerMockRecorder) SentTransactions(ctx, filter, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SentTransactions", reflect.TypeOf((*MockRelayer)(nil).SentTransactions), ctx, filter, page)
}

// Simulate mocks base method.
func (m *MockRelayer) Simulate(ctx context.Context, wallet, transactions string) ([]*proto.SimulateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Simulate", ctx, wallet, transactions)
	ret0, _ := ret[0].([]*proto.SimulateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Simulate indicates an expected call of Simulate.
func (mr *MockRelayerMockRecorder) Simulate(ctx, wallet, transactions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Simulate", reflect.TypeOf((*MockRelayer)(nil).Simulate), ctx, wallet, transactions)
}

// UpdateGasSponsor mocks base method.
func (m *MockRelayer) UpdateGasSponsor(ctx context.Context, projectId, id uint64, name *string, active *bool) (bool, *proto.GasSponsor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGasSponsor", ctx, projectId, id, name, active)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*proto.GasSponsor)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateGasSponsor indicates an expected call of UpdateGasSponsor.
func (mr *MockRelayerMockRecorder) UpdateGasSponsor(ctx, projectId, id, name, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGasSponsor", reflect.TypeOf((*MockRelayer)(nil).UpdateGasSponsor), ctx, projectId, id, name, active)
}

// UpdateGasTank mocks base method.
func (m *MockRelayer) UpdateGasTank(ctx context.Context, id uint64, name *string, feeMarkupFactor *float64, unlimited *bool) (bool, *proto.GasTank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGasTank", ctx, id, name, feeMarkupFactor, unlimited)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*proto.GasTank)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateGasTank indicates an expected call of UpdateGasTank.
func (mr *MockRelayerMockRecorder) UpdateGasTank(ctx, id, name, feeMarkupFactor, unlimited any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGasTank", reflect.TypeOf((*MockRelayer)(nil).UpdateGasTank), ctx, id, name, feeMarkupFactor, unlimited)
}

// UpdateMetaTxnGasLimits mocks base method.
func (m *MockRelayer) UpdateMetaTxnGasLimits(ctx context.Context, walletAddress string, walletConfig any, payload string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetaTxnGasLimits", ctx, walletAddress, walletConfig, payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetaTxnGasLimits indicates an expected call of UpdateMetaTxnGasLimits.
func (mr *MockRelayerMockRecorder) UpdateMetaTxnGasLimits(ctx, walletAddress, walletConfig, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetaTxnGasLimits", reflect.TypeOf((*MockRelayer)(nil).UpdateMetaTxnGasLimits), ctx, walletAddress, walletConfig, payload)
}

// Version mocks base method.
func (m *MockRelayer) Version(ctx context.Context) (*proto.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version", ctx)
	ret0, _ := ret[0].(*proto.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Version indicates an expected call of Version.
func (mr *MockRelayerMockRecorder) Version(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockRelayer)(nil).Version), ctx)
}
